### ISSUE TITLE
Installation not possible in Fedora29

### ISSUE THREAD

**Issue by dschier-wtd** [F-i-f/ssh-search-provider#2]
Hey, I am using Fedora 29 - Workstation and am getting an error during the installation of the extension. I don't know, if this may a problem with my setup (gnome-terminal is removed) or with the distro / shell version.

May you have a look in it? If something is needed from my side to debug the issue, please feel free to reach out to me.

Thanks for the awesome idea. I hope to get it running soon.

**Comment by F-i-f** [comment]
I haven't really tested without gnome-terminal installed.  I'll see if I can reproduce the issue.
What terminal emulator are you using?

**Comment by dschier-wtd** [comment]
I am using tilix from the official fedora repositories.

**Comment by F-i-f** [comment]
I have confirmed that overriding the default from gnome-terminal doesn't seem to work.
Could you send the output of:
```shell
dconf dump /org/gnome/desktop/applications/terminal/
```
You also wrote that you're seeing an error during the installation of the extension, can you cut and paste this error?
Thank you.

**Comment by dschier-wtd** [comment]
The path dconf dump /org/gnome/desktop/applications/ does not exist in my dconf.

```
dconf dump /org/gnome/desktop/
/org/gnome/desktop/a11y/              /org/gnome/desktop/notifications/
/org/gnome/desktop/app-folders/       /org/gnome/desktop/peripherals/
/org/gnome/desktop/background/        /org/gnome/desktop/privacy/
/org/gnome/desktop/calendar/          /org/gnome/desktop/screensaver/
/org/gnome/desktop/datetime/          /org/gnome/desktop/search-providers/
/org/gnome/desktop/input-sources/     /org/gnome/desktop/sound/
/org/gnome/desktop/interface/         /org/gnome/desktop/wm/
/org/gnome/desktop/media-handling/    
```

during installation I can see the following logs:

```
Apr 07 23:41:08 nb01 gnome-shell[2150]: JS WARNING: [resource:///org/gnome/shell/ui/extensionDownloader.js 86]: reference to undefined property "GLocalFileOutputStream"
Apr 07 23:41:08 nb01 org.gnome.Shell.desktop[2150]: Archive:  /tmp/B93PZZ.shell-extension.zip
Apr 07 23:41:08 nb01 org.gnome.Shell.desktop[2150]:   inflating: /home/ds/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org/extension.js
Apr 07 23:41:08 nb01 org.gnome.Shell.desktop[2150]:  extracting: /home/ds/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org/metadata.json
Apr 07 23:41:08 nb01 gnome-shell[2150]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Apr 07 23:41:08 nb01 gnome-shell[2150]: Extension "ssh-search-provider@extensions.gnome-shell.fifi.org" had error: TypeError: Shell.AppSystem.get_default(...).lookup_app(...) is null
```

**Comment by F-i-f** [comment]
Thank you.

There were two issues:
- The extension failed when gnome-terminal wasn't installed.
- The extension wasn't building the command line properly if another terminal emulator than gnome-shell was used.

Both issues should have been addressed.
Please try this zip file:
[ssh-search-provider@extensions.gnome-shell.fifi.org-v3-7-g13d6d33.zip](https://github.com/F-i-f/ssh-search-provider/files/3052231/ssh-search-provider%40extensions.gnome-shell.fifi.org-v3-7-g13d6d33.zip)
Just unzip it under `~/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org` and overwrite the files.

If you want to use something else than gnome-terminal as terminal emulator, please follow the instructions on the [home page](https://github.com/F-i-f/ssh-search-provider#selecting-your-preferred-terminal-application).

And please report if the bug is fixed or not, with the relevant output of:
```shell
dconf dump /org/gnome/desktop/applications/terminal/
journalctl -b
```

Thank you.

**Comment by dschier-wtd** [comment]
With the provided fix, the extension can be enabled and presents some login possibilities.

Since the above path is not present in my installation, I am not sure where to change the terminal. I will check and open another issue, if needed. The installation seems to work for now.

Thanks a lot for having a look!

**Comment by dschier-wtd** [comment]
my fault, the path exists in dconf.

Nevertheless, the shell is not quite the same as presented by your screenshots.

**Comment by dschier-wtd** [comment]
![Screenshot from 2019-04-08 21-18-02](https://user-images.githubusercontent.com/6490538/55750599-ee5ea700-5a43-11e9-9fc1-cbfb4e41ca99.png)

**Comment by F-i-f** [comment]
You are right.  That was because the extension was still relying on Gnome-Terminal to be around.
It took some work to completely get rid of it.
Please try this update:
[ssh-search-provider@extensions.gnome-shell.fifi.org-v3-24-g2ac5967.zip](https://github.com/F-i-f/ssh-search-provider/files/3065954/ssh-search-provider%40extensions.gnome-shell.fifi.org-v3-24-g2ac5967.zip)
Just unzip it under ~/.local/share/gnome-shell/extensions/ssh-search-provider@extensions.gnome-shell.fifi.org and overwrite the files.

Note that you must now configure your terminal emulator of choice in the extension preferences (Gnome Tweaks > Extensions > SSH Search Provider Reborn > Gear Icon (disregard the old instructions on the web page).  Select "Tilix" as a Terminal Emulator, and the defaults should work out of the box.

**Comment by dschier-wtd** [comment]
Hey,
I have tested the above code and everything is looking awesome :)

Thanks a ton for the fast help and for maintaining the extension.

**Comment by F-i-f** [comment]
I have released version 4 which fixes the problem.
It's currently under review by the gnome-shell team.
In meantime you can get it from the [project homepage](https://github.com/F-i-f/ssh-search-provider/) or download [version 4 directly here](https://github.com/F-i-f/ssh-search-provider/releases/download/v4/ssh-search-provider@extensions.gnome-shell.fifi.org.v4.shell-extension.zip).
